version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vehiclemanagement
      MYSQL_USER: cst8319
      MYSQL_PASSWORD: cst8319
    volumes:
      - ./v1/src/main/resources/sql:/docker-entrypoint-initdb.d

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
