# Updated from original cst8288/vehiclemanagment to correct spelling and new credentials
# Make sure your MySQL has this database and user set up before running
jdbc.url=jdbc:mysql://localhost:3306/vehiclemanagement
jdbc.username=cst8319
jdbc.password=cst8319
#change local host to db for submission