package app.repository;

import app.model.Notification;
import app.util.DatabaseConnection;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/*
 * This is the only class that touches the database for US.3 and US.5.
 * Sprint 4: now uses the DatabaseConnection singleton instead of its
 * own copy of the property-loading logic.
 */
public class NotificationRepository {
	/*
	 * Sprint 4: switched to the team's shared singleton instead of loading
	 * database.properties ourselves. One source of truth for DB credentials across
	 * the whole application.
	 */
	private Connection getConnection() throws SQLException {
		return DatabaseConnection.INSTANCE.getConnection();
	}

	/*
	 * This puts notification data into the notification table in the database the
	 * String uses ? to inject string values into the prepared statement for
	 * security the id and the submitted_At are not added as they are generated by
	 * MySQL directly so it's unnecessary
	 */
	public void insert(Notification notification) throws SQLException {
		String sql = "INSERT INTO notifications (vehicle, customer_name, customer_email, message) VALUES (?, ?, ?, ?)";

		try (Connection conn = getConnection(); PreparedStatement stmt = conn.prepareStatement(sql)) {

			stmt.setString(1, notification.getVehicle());
			stmt.setString(2, notification.getCustomerName());
			stmt.setString(3, notification.getCustomerEmail());
			stmt.setString(4, notification.getMessage());

			stmt.executeUpdate();
		}
	}

	/*
	 * Gets all the rows in the notifications table as a list of Notification
	 * objects Ordered by submitted_at DESC so the newest inquiry always appears at
	 * the top of the staff table The ResultSet loops through each row and builds a
	 * Notification object from it
	 */
	public List<Notification> getAll() throws SQLException {
		List<Notification> notifications = new ArrayList<>();
		String sql = "SELECT id, vehicle, customer_name, customer_email, message, submitted_at FROM notifications ORDER BY submitted_at DESC";

		try (Connection conn = getConnection();
				PreparedStatement stmt = conn.prepareStatement(sql);
				ResultSet rs = stmt.executeQuery()) {

			while (rs.next()) {
				Notification n = new Notification(rs.getInt("id"), rs.getString("vehicle"),
						rs.getString("customer_name"), rs.getString("customer_email"), rs.getString("message"),
						rs.getString("submitted_at"));
				notifications.add(n);
			}
		}
		return notifications;
	}

	/*
	 * Deletes a single notification row by its id Called when a staff member clicks
	 * the Delete button on the notifications page
	 */
	public void delete(int id) throws SQLException {
		String sql = "DELETE FROM notifications WHERE id = ?";

		try (Connection conn = getConnection(); PreparedStatement stmt = conn.prepareStatement(sql)) {

			stmt.setInt(1, id);
			stmt.executeUpdate();
		}
	}
}