package app.repository;

import app.model.Notification;

import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;


/*
 * This is the only class that touches the the db.
 * The servlets use this class to access the notification data
 * This is the key of MVC architecture
 */
public class NotificationRepository {

	/*
	 * This opens a connection to the database using the database.properties file
	 * The current version is not using the singleton pattern due to some issues in development this will be fixed in sprint 4
	 */
    private Connection getConnection() throws SQLException {
        Properties props = new Properties();
        try {
            InputStream input = getClass().getClassLoader()
                    .getResourceAsStream("database.properties");
            props.load(input);
        } catch (IOException e) {
            throw new SQLException("Could not load database.properties", e);
        }

        String url = props.getProperty("jdbc.url");
        String username = props.getProperty("jdbc.username");
        String password = props.getProperty("jdbc.password");

        return DriverManager.getConnection(url, username, password);
    }

    /*
     * This puts notification data into the notification table in the database
     * the String uses ? to inject string values into the prepared statement for security
     * the id and the submitted_At are not added as they are generated by MySQL directly so it's unnecessary
     */
    public void insert(Notification notification) throws SQLException {
        String sql = "INSERT INTO notifications (vehicle, customer_name, customer_email, message) VALUES (?, ?, ?, ?)";

        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, notification.getVehicle());
            stmt.setString(2, notification.getCustomerName());
            stmt.setString(3, notification.getCustomerEmail());
            stmt.setString(4, notification.getMessage());

            stmt.executeUpdate();
        }
    }

    /*
     * Gets all the rows in the notifications table as a list of Notification objects
     * Ordered by submitted_at DESC so the newest inquiry always appears at the top of the staff table
     * The ResultSet loops through each row and builds a Notification object from it
     */
    public List<Notification> getAll() throws SQLException {
        List<Notification> notifications = new ArrayList<>();
        String sql = "SELECT id, vehicle, customer_name, customer_email, message, submitted_at FROM notifications ORDER BY submitted_at DESC";

        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                Notification n = new Notification(
                        rs.getInt("id"),
                        rs.getString("vehicle"),
                        rs.getString("customer_name"),
                        rs.getString("customer_email"),
                        rs.getString("message"),
                        rs.getString("submitted_at")
                );
                notifications.add(n);
            }
        }
        return notifications;
    }
    /*
     * Deletes a single notification row by its id
     * Called when a staff member clicks the Delete button on the notifications page
     */
    public void delete(int id) throws SQLException {
        String sql = "DELETE FROM notifications WHERE id = ?";

        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, id);
            stmt.executeUpdate();
        }
    }
}